---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: core-services
  destination:
    name: "in-cluster"
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.1
    chart: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
