apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  expose:
    type: service
  spinnakerConfig:
    config:
      security:
        apiSecurity:
          overrideBaseUrl: https://spinnaker-api.mist-chicken.ts.net
          corsAccessPattern: https://spinnaker-api.mist-chicken.ts.net
        uiSecurity:
          overrideBaseUrl: https://spinnaker.mist-chicken.ts.net
      version: 2025.2.2
