---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: core-services
  destination:
    name: "in-cluster"
    namespace: traefik
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 35.3.0
    chart: traefik
    helm:
      parameters:
        - name: service.type
          value: NodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
