---
- name: Create persistence folder
  ansible.builtin.file:
    path: "{{ persistence_folder }}"
    state: directory
    mode: "0755"

- name: Create haproxy container (Proxmox)
  ansible.builtin.include_tasks:
    file: pve.yml
  when: inventory_hostname in groups['pve']

- name: Create haproxy container (Proxmox)
  ansible.builtin.include_tasks:
    file: unraid.yml
  when: inventory_hostname in groups['unraid']
