---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-tailscale
  finalizers:
    - tailscale.com/finalizer
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: jenkins-operator-http-jenkins
      port:
        number: 8080
  tls:
    - hosts:
        - jenkins
