---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: speedtest-tracker-secrets
  namespace: speedtest-tracker
spec:
  encryptedData:
    APP_KEY: AgDw7SrUdUMByEFNKYLJnwkpINDYFQVW1t9WmVbvSYK3oFr1wbvljFbJj5+ftZYTej24kKWElMY5pOxsfil4Qv06Wav0oIj2FwPx/AQlnM6b+N0dQqzYhXb0g4RbPiWFK2025uTIIVRCChTPEr+ZmVjKA+zTKWINKOPw1yQRDG/WmIGY+JDr0KdWimDKemudcQf63U+Ff0qMby51IkVzqKiatIDo2LLeOe970Yh0JAWnf2X29J6elIW9PgsNgGQM23UPxeBHcLwJePkin4suMtJk/0lyfk8Jx+7njMnQQ/nj9HJ//ncPNSM0xhcgcsbWNoikcmKLJJa4nuemw0R//ZLrb5Ox3JT6/keCmg9qmgZKqXC6ee4QtJIXjqBXdxGSQAApshG+SPdup1rErEEcPqCojva2d5Ic/6oQ9e9Gg1l22Yfy7eE2FFerar5H9RSsdHS+XJnqc6HlIgi9kLBB5Esn5NXRCMzkvhqR4rsuv5Nizkr+MA1oieuva5x5LB1iB2vbxyb5M6nk5tCJ73AZwtuCmP6x6V4+UpMM8uUPaAZrLgQfwgmxry7Ub5ZGWx/almf3HRD9AbjFDG/7eb2Izk5o5IFcUUq6EmWI3wNErQUrl82t6uN/ZztAGzKx4cvquAYHI61PpDekBRpHKm+mwUHc7FkMn/yAQ5qSrLPILNsv3ojmSgPj1f6OLXZe6XRICPvJOFliYKVwGF/41WzXV00a9qEussU5fEtrQ7ZsX5277WTzwKWJrJ+kvb+/NR6FHXd4d2k=
  template:
    metadata:
      creationTimestamp: null
      name: speedtest-tracker-secrets
      namespace: speedtest-tracker
