---
- name: Generate haproxy configuration (all)
  hosts: all
  gather_facts: false
  vars_files:
    - defaults.yaml
  tasks:
    - name: Create haproxy configuration
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /tmp/haproxy.cfg
        mode: "0644"

## Proxmox servers ############################################################

- name: Deploy haproxy load balancers (PVE)
  hosts: pve
  gather_facts: false
  vars:
    pve_id: "{{ pve_use_ids_from + 1 }}"
  tasks:
    - name: Check container status
      ansible.builtin.command: pct status {{ pve_id }}
      register: container_status
      changed_when: false
      failed_when: false

    - name: Create haproxy container
      ansible.builtin.shell: |
        pveam download {{ pve_template_storage }} {{ pve_container_template }}
        pct create {{ pve_id }} {{ pve_template_storage }}:vztmpl/{{ pve_container_template }} \
            --cores 1 --memory 256 --swap 0 --hostname okd-haproxy \
            --net0 name=eth0,bridge=vmbr0,ip=dhcp,type=veth,hwaddr={{ pve_haproxy_mac_address }} \
            --storage {{ pve_container_storage }} --onboot 1
      when: '"status" not in container_status.stdout'
      register: container_create
      changed_when: '"container architecture" in container_create.stdout'

    - name: Check container status
      ansible.builtin.command: pct status {{ pve_id }}
      register: container_status
      changed_when: false
      failed_when: false

    - name: Start haproxy container
      ansible.builtin.shell: |
        pct start {{ pve_id }}
        pct exec {{ pve_id }} -- sh -c 'apk upgrade && apk add haproxy'
        pct push {{ pve_id }} /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg
        pct exec {{ pve_id }} -- sh -c 'rc-update add haproxy && rc-service haproxy start'
      when: '"status: stopped" in container_status.stdout'
      register: container_start
      changed_when: '"Starting haproxy" in container_start.stdout'

## Unraid servers #############################################################

- name: Deploy haproxy load balancers (Unraid)
  hosts: unraid
  gather_facts: false
  vars_files:
    - defaults.yaml

  tasks:
    - name: Create haproxy container for Unraid servers
      ansible.builtin.shell: |

        echo "Hi!"
      register: create_container_output
      changed_when: '"Hi!" not in create_container_output.stdout'

    - name: Create haproxy container output
      ansible.builtin.debug:
        var: create_container_output
