---
- name: Destroy haproxy load balancers
  hosts: pve
  gather_facts: false
  vars_files:
    - defaults.yml

  tasks:
    - name: Remove haproxy container
      ansible.builtin.shell:
        cmd: |
          pct stop {{ pve_loadbalancer_id }}
          pct destroy {{ pve_loadbalancer_id }}
        removes: /etc/pve/lxc/{{ pve_loadbalancer_id }}.conf
      register: remove_container

    - name: Show debug output
      ansible.builtin.debug:
        var: remove_container
        verbosity: 2

    - name: Remove persistence folder
      ansible.builtin.file:
        path: "{{ persistence_folder }}"
        state: absent
      when: persistence_cleanup | bool

    - name: Remove openshift installer
      ansible.builtin.file:
        path: "/usr/local/bin/openshift-install"
        state: absent
      when: persistence_cleanup | bool

###

- name: Destroy OpenShift machines
  hosts: pve
  gather_facts: false
  vars_files:
    - defaults.yml
    - okd-server/defaults/main.yml

  tasks:
    - name: Destroy bootstrap machine
      ansible.builtin.shell:
        cmd: |
          qm stop {{ pve_bootstrap_id }}
          qm destroy {{ pve_bootstrap_id }}
        removes: /etc/pve/qemu-server/{{ pve_bootstrap_id }}.conf
      register: destroy_vm

    - name: Destroy control planes
      vars:
        template_id: "{{ pve_controlplane_ids_start_from + index }}"
      ansible.builtin.shell:
        cmd: |
          qm stop {{ template_id }}
          qm destroy {{ template_id }}
        removes: /etc/pve/qemu-server/{{ template_id }}.conf
      register: destroy_vm
      loop: "{{ controlplane_ips }}"
      loop_control:
        index_var: index

    - name: Destroy worker nodes
      vars:
        template_id: "{{ pve_worker_ids_start_from + index }}"
      ansible.builtin.shell:
        cmd: |
          qm stop {{ template_id }}
          qm destroy {{ template_id }}
        removes: /etc/pve/qemu-server/{{ template_id }}.conf
      register: destroy_vm
      loop: "{{ worker_ips }}"
      loop_control:
        index_var: index

    - name: Destroy template machine
      ansible.builtin.command:
        cmd: qm destroy {{ pve_scos_template_id }}
        removes: /etc/pve/qemu-server/{{ pve_scos_template_id }}.conf
      register: destroy_vm
