---
- name: Destroy haproxy load balancers
  hosts: unraid
  gather_facts: false
  vars_files:
    - defaults.yml
    - okd-server/defaults/main.yml

  tasks:
    - name: Destroy haproxy container
      community.docker.docker_compose_v2:
        project_src: "{{ unraid_haproxy_compose_project }}"
        state: absent
        remove_images: all
      failed_when: false

    - name: Destroy bootstrap machine
      vars:
        vm_files_path: "{{ unraid_vms_path }}/{{ bootstrap_name }}"
        vm_name: "{{ bootstrap_name }}"
      ansible.builtin.include_tasks:
        file: okd-server/tasks/unraid-destroy-vm.yml

    - name: Destroy control planes
      vars:
        vm_files_path: "{{ unraid_vms_path }}/{{ controlplane_name }}{{ index }}"
        vm_name: "{{ controlplane_name }}{{ index }}"
      ansible.builtin.include_tasks:
        file: okd-server/tasks/unraid-destroy-vm.yml
      loop: "{{ controlplane_ips }}"
      loop_control:
        index_var: index

    - name: Destroy worker nodes
      vars:
        vm_files_path: "{{ unraid_vms_path }}/{{ worker_name }}{{ index }}"
        vm_name: "{{ worker_name }}{{ index }}"
      ansible.builtin.include_tasks:
        file: okd-server/tasks/unraid-destroy-vm.yml
      loop: "{{ worker_ips }}"
      loop_control:
        index_var: index

    - name: Remove persistence folder
      ansible.builtin.file:
        path: "{{ persistence_folder }}"
        state: absent

    - name: Remove appdata folder
      ansible.builtin.file:
        path: "{{ unraid_haproxy_appdata }}"
        state: absent
