---
- name: Destroy haproxy load balancers
  hosts: unraid
  gather_facts: false
  vars_files: defaults.yaml

  tasks:
    - name: Destroy haproxy container
      community.docker.docker_compose_v2:
        project_src: "{{ unraid_haproxy_compose_project }}"
        state: absent
        remove_images: all

    - name: Remove persistence folder
      ansible.builtin.file:
        path: "{{ persistence_folder }}"
        state: absent

    - name: Remove appdata folder
      ansible.builtin.file:
        path: "{{ unraid_haproxy_appdata }}"
        state: absent
