apiVersion: v1
baseDomain: localdomain
metadata:
  name: okd
compute:
  - name: worker
    replicas: 0
    platform: {}
controlPlane:
  name: master
  replicas: 3
  platform: {}
platform:
  none: {} # OKD requires this field to signal no cloud provider
pullSecret: '{"auths": ...}' # https://console.redhat.com/openshift/install/pull-secret
sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHoO/4gD+BonVkdLKmArZPoISGar0yIWHX8HABbfIpgC miles@Miless-MBP.local"
networking:
  networkType: OVNKubernetes
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 192.168.1.0/24
