---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
spec:
  project: apps
  destination:
    name: "in-cluster"
    namespace: gitlab-system
  source:
    repoURL: https://github.com/CrouchingMuppet/k8s-home-lab.git
    path: apps/gitlab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
