---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: speedtest-tracker
  source:
    repoURL: https://github.com/CrouchingMuppet/k8s-home-lab.git
    path: apps/speedtest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
