---
apiVersion: v1
kind: ConfigMap
metadata:
  name: duckdns-config
data:
  PUID: "100"
  PGID: "99"
  TZ: Australia/Brisbane
  UMASK: "22"
  SUBDOMAINS: fluster,parfitt,dont-give-a,wot-the,crouchingmuppet
