---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-secrets
  namespace: duckdns
spec:
  encryptedData:
    TOKEN: AgAqLw5ug2WE5m2OrWbLRPv+fA5arv2WHJr7+k59zYX79ObPxGyT/Tzu98OZCqPnWfEQgfzRrho9jPOJjZWsXHX8SBZq6p2FOznX8yvozoPpcvePk0f+0srHvKvcjoL4ML2hqdCtf8QfA9rpprvZbMC4XmNEvRDmrZynnBdCN0N2J0cF8uQy0anLrDygSStFCHk/ZJbADieNYaPGSSjO5Spg3Z5YkrSs5y9UGe7vTHx+U5XWeCARvmp6OGQQm4tsRxpC6w2cuYVLlDLPSBQFI2V69l3a402oN9EcBIUVtDuGsR78C3BpfyHnhGgPPGhZEW4kWd7/UquCzrUO5gyrj/BIdCMWJcICRfzxiNynnblg7Noyjp3r9fcYJWY8/g61+WmMAX2rDNpPEOhZl14Igrz1e21FDoQthMvdsivXO+PkH547b8LmMBNp9L7b3HVr2PUHfNjwjCtSapGf+gS2rN5ZJuWFhhlm1hQV/YqgD2Thlch3Tz2NnwJUAvy823pxQeDjMbXWxuVjlTmbsK3qmcjVFYNo3rOoDCebtUR+hBLLkcUbLvxyutuqkwKJ5i8wwWQ52R+Iw5NYHilk0LXTiwDoyZNMu3jEnLLFyluFpCbBilxaA509ptn24uQfUQO+CTjDkKUQe70B3bdNEtMo6NDtJNJAwjtDr8jRXEIKNeL1CIMjbBPmZqGyeMTRPBO/BuWSP9kYCG11qg37w3OA+vVlGpW7iSo7CdcdGpPCVgFia2NSgjQ=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-secrets
      namespace: duckdns
