---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: core-services
  destination:
    name: "in-cluster"
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.0
    chart: longhorn
    helm:
      parameters:
        - name: preUpgradeChecker.jobEnabled
          value: "false"
        - name: csi.attacherReplicaCount
          value: "1"
        - name: csi.provisionerReplicaCount
          value: "1"
        - name: csi.resizerReplicaCount
          value: "1"
        - name: csi.snapshotterReplicaCount
          value: "1"
        - name: ui.replicaCount
          value: "1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
